Python test suites
m-danya/prolog-testing-system pull request #7
Opened 2023-01-05 16:47 UTC by NotLebedev

Добавлена поддержка тестов на питоне.

2023-01-10 15:54 UTC, m-danya requested changes
Запустил, работает, здорово!! 

Оставил комменты, поправь, пожалуйста. Вот ещё два окологлобальных пункта:

1) Мы используем pathlib вместо os.path. Она круче, понятнее, читаемей, совместимее [и тд](https://towardsdatascience.com/why-you-should-start-using-pathlib-as-an-alternative-to-the-os-module-d9eccd994745), я там местами написал, как че переписать, выглядеть стало прям почитаемее)
2) После правок пропусти, пожалуйста, код через black:
```bash
pip install black
black ./api
```
Добавлю в ридмишку, кстати, про это

2023-01-10 15:54 UTC, m-danya commented on api/prolog_parsing.py
> +    valid_exts = ['.ans', '.py']
можно вынести как константу в `api/settings.py`, а можно и не выносить

2023-01-10 15:54 UTC, m-danya commented on api/prolog_parsing.py
> +            if os.path.exists(test_ans):
лучше `test_ans.exists()`, мы юзаем pathlib вместо os.path

2023-01-10 15:54 UTC, m-danya commented on api/prolog_parsing.py
> +    ext = os.path.splitext(test_ans)[-1].lower()
`ext = test_ans.suffix.lower()`, аналогично про pathlib vs os.path

2023-01-10 15:54 UTC, m-danya commented on api/prolog_parsing.py
> +        '')
пустая строка + black

2023-01-10 15:54 UTC, m-danya commented on api/prolog_parsing.py
> +    test_ans = os.path.splitext(test_ans)[0]
`test_ans = test_ans.stem`

2023-01-10 15:54 UTC, m-danya commented on api/prolog_parsing.py
> +    test_ans = test_ans.replace('/', '.')
если юзать pathlib (а мы хотим его юзать везде, где можно), то тогда тут уже придётся явно в строку сконвертить:

`test_ans = str(test_ans).replace(...)`

2023-01-10 15:54 UTC, m-danya commented on api/prolog_parsing.py
> +    test_ans = str(test_ans)
это тогда минус строка

2023-01-10 15:54 UTC, m-danya commented on api/prolog_parsing.py
> +    test_dir = '/'.join(test_ans.split('.')[:-1])
`test_dir = test_ans.parent`
ну только надо с именами поиграться, чтобы в `test_ans` всё ещё лежал объект из аргументов

2023-01-10 15:54 UTC, m-danya commented on api/prolog_parsing.py
> +    #test_ans = test_ans.split('.')[-1]
del

2023-01-10 15:54 UTC, m-danya commented on api/prolog_parsing.py
> +    sys.path.append(test_dir)
твой рассказ о том, что тут происходит, меня впечатлил, наверное, тут всё норм) разве что можно обренуть в try/except/finally, чтобы в любом случае срабатывало `sys.path.remove(test_dir)`, даже если в строках между случилась ошибка (а такое вполне может быть)

2023-01-10 15:54 UTC, m-danya commented on api/prolog_parsing.py
> +    func = getattr(test_module, 'test_result')
а через точку здесь нельзя сделать? просто `func = test_module.test_result`

2023-01-10 15:54 UTC, m-danya commented on api/prolog_parsing.py
> +def test_result_equal(output_lines, test_ans, test_number):
мб поменять название на что-то типа "test_with_dumb_equality" / "test_with_straightforward_comparing"?

2023-01-10 15:54 UTC, m-danya commented on api/tests/task_7_2_2/common.py
> +        return (test_number, "TL", output_lines, correct_lines)
лишние скобки тут и в строках ниже

2023-01-10 15:54 UTC, m-danya commented on api/tests/task_7_2_2/common.py
> +def test(output_lines, test_number, correct_lines, expected):
получается жёсткое дублирование кода с проверкой ошибок... Ладно с кодом, который проверяет как раньше, тут отличается половина, но щас получается, что для каждой задачи нужно будет дублировать этот код (проверку на TL/RE/WA) в `common.py` для каждой задачи.. Может этот код вынести куда-то в `api` и из этого файла уже вызывать?

2023-01-10 15:54 UTC, m-danya commented on api/tests/task_7_2_2/common.py
> +    p = re.compile(r'Result = \[\[\[(.*?)\]\]\]')
я бы для ясности сюда добавил коммент типа
`# parsing a string like "Result = [[[1,3,5,17]]]"`
В тч потому что дальше тоже важно понимать, что там просто числа через запятую. Для нас ща это очевидно, а в будущем люди могут испугаться))

2023-01-10 15:54 UTC, m-danya commented on api/tests/task_7_2_2/common.py
> +    if nums != expected:
и тут коммент типа "ответ считается правильным, если является перестановкой заданного списка чисел"

2023-01-10 15:54 UTC, m-danya commented on api/tests/task_7_2_2/test_1.py
> +correct_lines = ['Result = [[[1,3,5]]]', 'yes']
а зачем это вообще тут нужно, если числа проверяются по `expected`?
можно хранить просто кол-во строк, а то щас выглядит как дублирование информации)

2023-01-10 15:54 UTC, m-danya commented on api/tests/task_7_2_2/test_1.py
> +expected = set([1, 3, 5])
тут можно покрасивее написать: `{1, 3, 5}`

2023-01-10 15:54 UTC, m-danya commented on api/tests/task_7_2_2/test_2.py
> +expected = set([1, 3, 5, 17])
аналогично по этим двум строкам

2023-01-17 18:51 UTC, m-danya commented
Ты ещё не допилил, да?

2023-01-29 09:05 UTC, NotLebedev commented on api/tests/task_7_2_2/test_1.py
> +correct_lines = ['Result = [[[1,3,5]]]', 'yes']
Нужно выдавать ответ какой результат считается правильным

2023-01-29 09:33 UTC, NotLebedev commented on api/tests/task_7_2_2/common.py
> +def test(output_lines, test_number, correct_lines, expected):
В теории тест может ожидать завершение с RE или TL и обрабатывать это как-то по особенному. Копипасту переделал

2023-01-29 09:33 UTC, NotLebedev commented
Готово

2023-01-29 15:02 UTC, m-danya commented
Кул, мне всё нравится, кроме вот этих мелочей. Спасибо за PR)
В идеале чтоб еще @sadimer глянул

2023-01-29 15:03 UTC, m-danya reviewed
Кул, мне всё нравится, кроме вот этих мелочей. Спасибо за PR)
В идеале чтоб еще @sadimer глянул

2023-01-31 09:19 UTC, NotLebedev commented
Сделано

2023-01-31 13:17 UTC, merged